# The name of this app. Must be unique within a project.
name: htmlhowto

# استخدام نوع Python كما هو مطلوب.
type: "python:3.7"

# إعداد التخزين، يمكنك زيادته إذا لزم الأمر.
disk: 256

# إعدادات خادم الويب.
web:
    commands:
        # عملية no-op للحفاظ على الخدمة قيد التشغيل بدون استهلاك موارد وحدة المعالجة المركزية.
        start: sleep infinity

    locations:
        # تقديم الملفات الثابتة من مجلد 'web'.
        "/":
            root: "web"
            index:
                - "index.html"
            expires: 1h  # مدة التخزين المؤقت، لتحسين الأداء مع Varnish.
