# routes.yaml
"https://{default}/":
    type: upstream
    upstream: "varnish:http"
    cache:
        enabled: true
        default_ttl: 3600  # مدة التخزين المؤقت الافتراضية (بالثواني)
    fallback: "app:http"
